language: swift
osx_image: xcode12
script:
  swift test -v --enable-code-coverage && llvm-cov report \
    .build/x86_64-apple-macosx/debug/ChessKitPackageTests.xctest/Contents/MacOS/ChessKitPackageTests \
    -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata \
    -ignore-filename-regex=".build|Tests" \
    -use-color
after_success:
  - bash <(curl -s https://codecov.io/bash)
