name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run tests
      run:
        swift test --enable-code-coverage && ls .build && cp -r .build .build-saved
    
    - name: Swift Coverage Conversion
      uses: sersoft-gmbh/swift-coverage-action@v2.0.1
      with:
        format: lcov
        search-paths: ./.build-saved
        output: .
    
    - name: Upload coverage
      run:
        curl -Os https://uploader.codecov.io/latest/macos/codecov
        chmod +x codecov
        ./codecov -t a40ba6bb-c21e-4e2b-8947-12bb0605a008
