name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test
    - name: swift-codecov
      uses: mattpolzin/swift-codecov-action@0.7.1
